---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 2
ratings:
  paths:
  - "**.inc"
  - "**.module"
  - "**.py"
exclude_paths:
- .pylintrc
- .travis.yml
- dist/
- tests/
- build/
