---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    exclude_fingerprints:
ratings:
  paths:
  - "**.inc"
  - "**.module"
  - "**.py"
exclude_paths:
- dist/
- tests/
- build/
